name: untitled
timestamp: 0
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1442615525
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
